# Uncomment this line to define a global platform for your project
platform :ios, "7.0"
inhibit_all_warnings!

target "Chat" do
  pod 'socket.IO', '~> 0.5'
  pod 'AFNetworking', '~> 2.3'
  pod 'Mantle', '~> 1.5'
  pod 'TSMessages', '~> 0.9'
  pod 'DBCamera', '~> 2.3'
  pod 'MBProgressHUD', '~> 0.8'
  pod 'URBMediaFocusViewController', '~> 0.5'
  pod 'ColorArt', '~> 0.1'
end

target "ChatTests" do

end

