# Uncomment this line to define a global platform for your project
platform :ios, "7.0"
inhibit_all_warnings!

target "Chat" do
  pod 'socket.IO', '~> 0.5'
  pod 'AFNetworking', '~> 2.2'
  pod 'HPGrowingTextView', '~> 1.1'
  pod 'Mantle', '~> 1.4'
  pod 'TSMessages', '~> 0.9'
  pod 'DBCamera', '~> 2.0'
  pod 'CRNavigationController', '~> 1.1'
end

target "ChatTests" do

end

